we were told that there was a syntax error, so I ran the script first

$ python3 fixme1.py
  File "/home/dre/picoMini/fixme1.py/fixme1.py", line 20
    print('That is correct! Here\'s your flag: ' + flag)
IndentationError: unexpected indent

It looks like the indentation got mixed up on the last line.
I removed the 2 spaces at the start of the line and ran it again

$ python3 fixme1.py
That is correct! Here's your flag: picoCTF{1nd3nt1ty_cr1515_05a3c38c}
